//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Share
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicant
    {
        public int Applicant_Id { get; set; }
        public Nullable<int> Vacancy_Id { get; set; }
        public string Applicant_FullName { get; set; }
        public string Applicant_FoneNumber { get; set; }
        public string Applicant_Email { get; set; }
        public string Skill { get; set; }
        public string PositionApply { get; set; }
        public string certificate { get; set; }
        public string suggestSalary { get; set; }
        public string Applicant_Address { get; set; }
        public string Applicant_IP { get; set; }
        public string Applicant_Desription { get; set; }
        public string Applicant_DateRegister { get; set; }
        public string Applicant_Admin_Accept { get; set; }
        public string Applicant_Result { get; set; }
        public string Applicant_Client_Confirm { get; set; }
    
        public virtual Vacancy Vacancy { get; set; }
    }
}
