//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Share
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interviewer
    {
        public int Interviewer_Id { get; set; }
        public Nullable<int> Schedule_Id { get; set; }
        public string Interviewer_Status { get; set; }
        public string Interviewer_Result { get; set; }
        public string Interviewer_Note { get; set; }
    
        public virtual Schedule Schedule { get; set; }
    }
}
