//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Share
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public Schedule()
        {
            this.Interviews = new HashSet<Interview>();
            this.Vacancys = new HashSet<Vacancy>();
        }
    
        public int Schedule_Id { get; set; }
        public string DateTime_Create { get; set; }
        public string Schedule_Date { get; set; }
    
        public virtual ICollection<Interview> Interviews { get; set; }
        public virtual ICollection<Vacancy> Vacancys { get; set; }
    }
}
