//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Share
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacancy
    {
        public Vacancy()
        {
            this.Applicants = new HashSet<Applicant>();
        }
    
        public int Vacancy_Id { get; set; }
        public Nullable<int> Schedule_Id { get; set; }
        public string Vacancy_Name { get; set; }
        public string Vacancy_WorkAddress { get; set; }
        public string Vacancy_TypeTime { get; set; }
        public string Vacancy_Salary { get; set; }
        public string Vacancy_Positions { get; set; }
        public Nullable<int> Vacancy_NumberPeople { get; set; }
        public string Vacancy_Skill { get; set; }
        public string Vacancy_Exp { get; set; }
        public string Vacancy_Gender { get; set; }
        public string Vacancy_Age { get; set; }
        public string Vacancy_Description { get; set; }
        public string Vacancy_DateStart { get; set; }
        public string Vacancy_DateEnd { get; set; }
        public string Vacancy_DateUp { get; set; }
        public string Vacancy_DateInterViewer { get; set; }
        public string Vacancy_TimeInterViewer { get; set; }
        public string Vacancy_Status { get; set; }
        public Nullable<int> Admin_Id { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual ICollection<Applicant> Applicants { get; set; }
    }
}
